### ISSUE TITLE
Starred notifications and their place in the app

### ISSUE THREAD

**Issue by tarebyte** [andrew/octobox#119]
This conversation is happening in a few threads so I'm just going to start it here.

In https://github.com/andrew/octobox/issues/114#issuecomment-268653902 @briannelson suggested that we make the Starred bucket it's own thing and show notifications whether or not they are part of the inbox of archived. This is mirrors the functionality of gmail.

However in https://github.com/andrew/octobox/pull/115#issuecomment-268673845 @knolleary countered that it should remain as a filter.

Thoughts?

**Comment by briannelson** [comment]
Here's the proposed UX for a Starred bucket.

* Inbox shows all notifications that haven't been explicitly archived (including starred)
* Archived shows all notifications that have been archived (including starred)
* Starred shows all starred notifications (archived or not)
* Inbox, Archived, and Starred can only be selected one at a time
* Status, Type, Reason, and Repo filters are toggle-able for Inbox, Archived, or Starred

I think that gives the most flexibility and keeps with the expected behavior (if I star a message, I want to be able to see it in a list of starred messages). The only thing we lose is not being able to see a list of starred Inbox messages vs starred Archive messages. Archiving is such a transient action, anyhow, that it'd be hard to remember which list of starred items the one you're looking for is in.

**Comment by knolleary** [comment]
Perhaps I'm too influences by the gmail model, but I see whether a notification has been starred or not as orthogonal to 'where' the notification is.

If you treat it as a filter then you can still achieve everything listed above and ALSO let you see starred notifications in just your inbox or the archive - even more flexible.

Once you factor in the UI changes around the filter breadcrumbs I've proposed in #115, it will be much more obvious to the user what the current view is showing them.

From a UX perspective, the 'Starred' link in the sidebar could set the filter to "is:starred" and clear any existing "in:inbox" / "in:archive" filter - so by default, clicking that link sets the filters such that you see all starred notifications wherever they exist. On the surface, you may then ask why treat starred as a different thing to inbox/archive - I can envisage a future feature of having a search box (again, influenced by gmail), where you can set much more interesting search criteria (like "is:starred in:archive" etc). It also leaves scope for other buckets to be added in the future alongside Inbox and Archive.

**Comment by andrew** [comment]
@knolleary A+++++

**Comment by briannelson** [comment]
@knolleary I like that a lot. My biggest issue is that Inbox and Archive were remaining selected, but I see the use-case for being able to filter by all of those independently.

![image](https://cloud.githubusercontent.com/assets/29120/21426095/fa5bdf36-c81a-11e6-8fab-5b35edb750b5.png)

**Comment by briannelson** [comment]
I think this is fairly resolved now.
